version: '3.8'

services:
  backend:
    image: katerinapenaloza/chatbot-backend:latest
    ports:
      - "80:80"
    env_file:
      - ./backend/.env 

  frontend:
    image: katerinapenaloza/chatbot-frontend:latest
    ports:
      - "81:81"
    depends_on:
      - backend
