name: Docker Build and Push (frontend)

#Declaracion del disparador
on:
  push:
    branches:
      - main

#Declaracion de trabajos
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      #Eleccion del codigo
      - name: Checkout code
        uses: actions/checkout@v2
      
      #Preparacion del entorno    
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      #Construccion de la imagen contenedor con nombre
      - name: Build Docker image
        run: docker build -t katerinapenaloza/chatbot-frontend:latest ./frontend

      #Login a docker
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      #Push del docker
      - name: Push the Docker image
        run: docker push katerinapenaloza/chatbot-frontend:latest
